export const ROUTES = {
  HOME: '/',
  CATALOG: '/catalog',
  MATERIAL: '/catalog/:id',
  COURSE_VIEWER: '/catalog/:id/learn',
  ADD_MATERIAL: '/add-material',
  COMMUNITIES: '/communities',
  COMMUNITY: '/communities/:slug',
  CHAT: '/chat',
  TASKS: '/tasks',
  MENTORS: '/mentors',
  MENTOR_DETAIL: '/mentors/:id',
  PROJECTS: '/projects',
  ROADMAP: '/roadmap',
  SCHEDULE: '/schedule',
  PROFILE: '/profile',
  USER_PROFILE: '/profile/:id',
  WALLET: '/wallet',
  LOGIN: '/login',
} as const;
