export const ROUTES = {
  HOME: '/',
  CATALOG: '/catalog',
  SMART_SEARCH: '/smart-search',
  MATERIAL: '/catalog/:id',
  COURSE_VIEWER: '/catalog/:id/learn',
  ADD_MATERIAL: '/add-material',
  TASKS: '/tasks',
  MENTORS: '/mentors',
  PROJECTS: '/projects',
  ROADMAP: '/roadmap',
  SCHEDULE: '/schedule',
  GROWGRADE: '/growgrade',
  PROFILE: '/profile',
  USER_PROFILE: '/profile/:id',
  WALLET: '/wallet',
  LOGIN: '/login',
} as const;
